name: CI and CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0
      - run: npm install
      - run: npm run build
      - run: npm run test

      - name: Deploy to Github Pages
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MY_REPO_TOKEN }}